"""
opensquad/tools/report.py
Generates a professional PDF Security Audit Report using fpdf2.
Sections: Cover → Executive Summary → Plan → Vulnerabilities → Code Diff → EVPC Score
"""
import os
import difflib
from datetime import datetime
from fpdf import FPDF

REPORT_DIR = "/tmp"

# ── Color palette ─────────────────────────────────────────────────────
C_BG_DARK    = (15,  32,  39)
C_BG_MID     = (32,  58,  67)
C_ACCENT     = (255, 65,  108)
C_TEXT_LIGHT = (226, 232, 240)
C_TEXT_DARK  = (30,  30,  30)
C_GREEN      = (34,  197, 94)
C_RED        = (239, 68,  68)
C_YELLOW     = (234, 179, 8)
C_BLUE       = (56,  189, 248)
C_WHITE      = (255, 255, 255)
C_LIGHT_GRAY = (245, 245, 245)
C_MID_GRAY   = (180, 180, 180)


class AuditReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)

    # ── Header / Footer ──────────────────────────────────────────────
    def header(self):
        if self.page_no() == 1:
            return
        self.set_fill_color(*C_BG_DARK)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_TEXT_LIGHT)
        self.set_xy(10, 3)
        self.cell(0, 6, "OpenSquad AI  |  Security Audit Report  |  CONFIDENTIAL", align="L")
        self.set_xy(-30, 3)
        self.cell(20, 6, f"Page {self.page_no()}", align="R")
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*C_MID_GRAY)
        self.cell(0, 10, f"Generated by OpenSquad AI  •  {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")

    # ── Helpers ──────────────────────────────────────────────────────
    def section_title(self, title: str, icon: str = ""):
        self.ln(4)
        self.set_fill_color(*C_BG_MID)
        self.set_text_color(*C_TEXT_LIGHT)
        self.set_font("Helvetica", "B", 13)
        self.cell(0, 10, f"  {icon}  {title}", ln=1, fill=True)
        self.set_text_color(*C_TEXT_DARK)
        self.ln(3)

    def body_text(self, text: str, size: int = 10):
        self.set_font("Helvetica", "", size)
        self.set_text_color(*C_TEXT_DARK)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def kv_row(self, key: str, value: str, color=None):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*C_BG_DARK)
        self.cell(45, 7, key + ":", border=0)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*(color or C_TEXT_DARK))
        self.cell(0, 7, str(value), ln=1)

    def badge(self, text: str, color: tuple):
        self.set_fill_color(*color)
        self.set_text_color(*C_WHITE)
        self.set_font("Helvetica", "B", 8)
        self.cell(28, 6, text, fill=True, align="C")

    def code_block(self, code: str, max_lines: int = 40):
        """Render a monospaced code block with dark background."""
        self.set_fill_color(30, 30, 46)
        self.set_text_color(180, 220, 180)
        self.set_font("Courier", "", 7)
        lines = code.splitlines()[:max_lines]
        for line in lines:
            display = line[:110] + ("..." if len(line) > 110 else "")
            self.cell(0, 4.5, display, ln=1, fill=True)
        if len(code.splitlines()) > max_lines:
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(*C_MID_GRAY)
            self.cell(0, 4, f"  ... ({len(code.splitlines()) - max_lines} more lines truncated)", ln=1)
            self.ln(4)
        self.set_text_color(*C_TEXT_DARK)
        self.ln(3)

    def diff_block(self, original: str, fixed: str, max_lines: int = 60):
        """Render unified diff with green/red line highlights."""
        diff = list(difflib.unified_diff(
            original.splitlines(keepends=True),
            fixed.splitlines(keepends=True),
            fromfile="Original",
            tofile="Patched",
            lineterm="",
        ))
        if not diff:
            self.body_text("No textual differences found.")
            return

        self.set_font("Courier", "", 7)
        for line in diff[:max_lines]:
            display = line.rstrip()[:110] + ("..." if len(line) > 110 else "")
            if line.startswith("+++") or line.startswith("---"):
                self.set_fill_color(50, 50, 70)
                self.set_text_color(150, 170, 200)
            elif line.startswith("@@"):
                self.set_fill_color(20, 50, 80)
                self.set_text_color(*C_BLUE)
            elif line.startswith("+"):
                self.set_fill_color(20, 60, 30)
                self.set_text_color(100, 220, 120)
            elif line.startswith("-"):
                self.set_fill_color(60, 20, 20)
                self.set_text_color(220, 100, 100)
            else:
                self.set_fill_color(30, 30, 46)
                self.set_text_color(180, 180, 180)
            self.cell(0, 4.2, display, ln=1, fill=True)

        if len(diff) > max_lines:
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(*C_MID_GRAY)
            self.cell(0, 4, f"  ... ({len(diff) - max_lines} more diff lines truncated)", ln=1)
            self.ln(2)

        self.set_text_color(*C_TEXT_DARK)
        self.ln(3)


# ── Public API ────────────────────────────────────────────────────────
def generate_pdf(
    issue:           str,
    plan:            list,
    original_code:   str,
    fixed_code:      str,
    vulnerabilities: list  = None,
    evpc_score:      float = None,
    test_output:     str   = None,
    filename:        str   = "unknown_file",
) -> str:
    """
    Generate a full security audit PDF report.
    Returns: absolute path to the saved PDF file.
    Raises:  OSError if the output directory is not writable.
    """
    pdf = AuditReport()

    # ════════════════════════════════════════════════════════════════
    # PAGE 1 — COVER
    # ════════════════════════════════════════════════════════════════
    pdf.add_page()

    pdf.set_fill_color(*C_BG_DARK)
    pdf.rect(0, 0, 210, 297, "F")

    pdf.set_fill_color(*C_ACCENT)
    pdf.rect(0, 0, 8, 297, "F")

    pdf.set_xy(20, 60)
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(*C_TEXT_LIGHT)
    pdf.cell(0, 18, "OpenSquad AI", ln=1)

    pdf.set_xy(20, 82)
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(*C_BLUE)
    pdf.cell(0, 10, "Security Audit Report", ln=1)

    pdf.set_xy(20, 96)
    pdf.set_fill_color(*C_ACCENT)
    pdf.rect(20, 96, 80, 1, "F")

    pdf.set_xy(20, 106)
    meta = [
        ("File Audited",  filename),
        ("Date",          datetime.now().strftime("%B %d, %Y  %H:%M UTC")),
        ("AI Team",       "Manager (Gemma 3 27B)  |  Developer (Gemma 3 27B)  |  Reviewer (Gemma 3 27B)"),
        ("Methodology",   "Autonomous Multi-Agent + EVPC Sandboxed Verification"),
    ]
    for label, value in meta:
        pdf.set_xy(20, pdf.get_y())
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*C_MID_GRAY)
        pdf.cell(55, 8, label)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*C_TEXT_LIGHT)
        pdf.multi_cell(0, 8, value)

    if evpc_score is not None:
        pdf.set_xy(20, 200)
        pdf.set_font("Helvetica", "B", 12)
        if evpc_score == 1.0:
            pdf.set_text_color(*C_GREEN)
            status_text = "EXECUTION VERIFIED  (EVPC: 1.0)"
        elif evpc_score == 0.5:
            pdf.set_text_color(*C_YELLOW)
            status_text = "PARTIAL VERIFICATION  (EVPC: 0.5)"
        elif evpc_score == 0.0:
            pdf.set_text_color(*C_RED)
            status_text = "VERIFICATION FAILED  (EVPC: 0.0)"
        else:
            pdf.set_text_color(*C_MID_GRAY)
            status_text = "UNVERIFIED  (Sandbox Unavailable)"
        pdf.cell(0, 10, status_text)

    pdf.set_xy(20, 270)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*C_MID_GRAY)
    pdf.cell(0, 6, "CONFIDENTIAL — Generated by OpenSquad Autonomous Multi-Agent System")

    # ════════════════════════════════════════════════════════════════
    # PAGE 2 — EXECUTIVE SUMMARY
    # ════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.set_fill_color(*C_LIGHT_GRAY)
    pdf.rect(0, 0, 210, 297, "F")

    pdf.section_title("Executive Summary", "")
    pdf.kv_row("Issue",      issue[:200])
    pdf.kv_row("File",       filename)
    pdf.kv_row("Audit Date", datetime.now().strftime("%Y-%m-%d %H:%M"))
    pdf.kv_row("Agent Team", "Manager · Developer · Reviewer")

    vuln_count = len(vulnerabilities) if vulnerabilities else 0
    evpc_label = f"{evpc_score:.1f} / 1.0" if evpc_score is not None else "Not Measured"

    pdf.ln(6)
    metrics = [
        ("Vulnerabilities Found", str(vuln_count), C_ACCENT),
        ("Patches Generated",     "1",             C_BLUE),
        ("EVPC Score",            evpc_label,      C_GREEN if evpc_score == 1.0 else C_YELLOW),
    ]
    for label, value, color in metrics:
        pdf.set_fill_color(*color)
        pdf.set_text_color(*C_WHITE)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(55, 14, value, fill=True, align="C", border=0)
    pdf.ln(16)
    for label, _, _ in metrics:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*C_MID_GRAY)
        pdf.cell(55, 5, label, align="C")
    pdf.ln(10)

    # ════════════════════════════════════════════════════════════════
    # REPAIR PLAN
    # ════════════════════════════════════════════════════════════════
    pdf.section_title("Repair Plan  (Manager Agent)", "")
    if plan:
        for i, step in enumerate(plan, 1):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*C_ACCENT)
            pdf.cell(10, 7, f"{i}.")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*C_TEXT_DARK)
            pdf.multi_cell(0, 7, str(step))
            pdf.ln(1)
    else:
        pdf.body_text("No plan generated.")

    # ════════════════════════════════════════════════════════════════
    # VULNERABILITIES
    # ════════════════════════════════════════════════════════════════
    if vulnerabilities:
        pdf.section_title("Vulnerability Details", "")
        severity_colors = {
            "CRITICAL": C_RED,
            "HIGH":     C_ACCENT,
            "MEDIUM":   C_YELLOW,
            "LOW":      C_BLUE,
        }
        for vuln in vulnerabilities[:15]:
            pdf.set_fill_color(*C_BG_MID)
            pdf.set_text_color(*C_TEXT_LIGHT)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 7,
                f"  {vuln.get('cwe_id','?')}  --  {vuln.get('name','Unknown')}",
                fill=True, ln=1,
            )
            sev   = vuln.get("severity", "UNKNOWN")
            color = severity_colors.get(sev, C_MID_GRAY)
            pdf.set_text_color(*C_TEXT_DARK)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(25, 6, "Severity:")
            pdf.badge(sev, color)
            pdf.ln(8)
            for key, label in [
                ("owasp",   "OWASP"),
                ("cvss",    "CVSS"),
                ("line",    "Line"),
                ("snippet", "Code"),
            ]:
                val = vuln.get(key)
                if val:
                    pdf.kv_row(label, str(val)[:120])
            pdf.ln(3)

    # ════════════════════════════════════════════════════════════════
    # PAGE 3 — CODE DIFF
    # ════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.set_fill_color(*C_LIGHT_GRAY)
    pdf.rect(0, 0, 210, 297, "F")

    pdf.section_title("Code Changes  (Before vs After)", "")
    pdf.diff_block(original_code, fixed_code, max_lines=80)

    # ════════════════════════════════════════════════════════════════
    # EVPC VERIFICATION
    # ════════════════════════════════════════════════════════════════
    pdf.section_title("EVPC Verification Result", "")
    if evpc_score is None:
        pdf.body_text("Sandbox verification was not available for this run.")
    else:
        label_map = {
            1.0: ("EXECUTION VERIFIED", C_GREEN),
            0.5: ("PARTIAL -- Runs but reviewer flagged issues", C_YELLOW),
            0.0: ("FAILED -- Patch did not pass sandbox", C_RED),
        }
        label, color = label_map.get(evpc_score, ("UNKNOWN", C_MID_GRAY))
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*color)
        pdf.cell(0, 10, f"EVPC Score: {evpc_score:.1f} / 1.0  --  {label}", ln=1)
        pdf.ln(3)

    if test_output:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*C_BG_DARK)
        pdf.cell(0, 7, "Sandbox Output:", ln=1)
        pdf.code_block(test_output[:800], max_lines=20)

    # ── Save ─────────────────────────────────────────────────────────
    os.makedirs(REPORT_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path  = os.path.join(REPORT_DIR, f"OpenSquad_Audit_{timestamp}.pdf")
    pdf.output(out_path)
    return out_path
